### ISSUE TITLE
Needs Update of Everything

### ISSUE THREAD

**Issue by AirDronzer** [erdalceylan/Acer-swift-3-sf315-52G-hackintosh-OC#1]
Opencore 0.6.5 and all kext got update Plz Update all Things and any fix for mic?

**Comment by erdalceylan** [comment]
I'm really busy and working hard I don't have time i , can update soon maybe you can use 
https://github.com/linhnguyengas/Hackintosh-Acer-Swift3-SF315-52G
if u can linhnguyengas repostrory fix wifi card another use Opencore 0.6.2 
Mic. not workin in Linux driver and hackintosh

good luck :)

**Comment by AirDronzer** [comment]
Thanks Buddy but I need ur favour I tried with linhnguyengas repo but I had issue of screen flickering. Plz If u Get Time update everything. Thank U :).

**Comment by erdalceylan** [comment]
@AirDronzer everything is updated
