### ISSUE TITLE
Big Sur EFI Bootloader can't boot

### ISSUE THREAD

**Issue by as209099** [erdalceylan/Acer-swift-3-sf315-52G-hackintosh-OC#2]
My laptop model is Acer swift 3 SF315-52G as same as yours.
I uesd your EFI in Catalina folder to install Mojave successfully, and itlwm kext is not working for Wifi, so I replace it to Airportitlwm kext, and it works!

But I am trying to install Catalina, the OC will crash and display crash, I have no idea about it.

Also, I use your EFI in Big Sur folder to boot, my screen not even show up to OC Bootloader.

Do you have any help about the issue?
Thanks.

**Comment by erdalceylan** [comment]
I'm planning to post an update for bigsur but not sure when

**Comment by as209099** [comment]
> I'm planning to post an update for bigsur but not sure when

Got it !
Thanks for pay a lot of works.

**Comment by erdalceylan** [comment]
@as209099 everything is updated

**Comment by as209099** [comment]
Thanks !
I will try it later :)
